version: '3'
services:
  categorical_variables:
    build: .
    image: categorical-variables:latest  # This matches your Dockerfile
    volumes:
      - ../../lessons/categorical_variables:/app/work
    ports:
      - "8888:8888"
